import os
import json
from dotenv import load_dotenv
from groq import Groq

load_dotenv()

client = Groq(api_key=os.environ.get("GROQ_API_KEY"))


def groq_signal(text: str) -> float:
    """
    Returns a float 0-1 representing the probability the text is AI-generated,
    based on the LLM's holistic semantic/stylistic judgment.
    """
    prompt = f"""You are an expert at detecting AI-generated text.
Analyze the following text and estimate the probability (0.0 to 1.0) that it was generated by an AI rather than written by a human.

Respond ONLY with a JSON object in this exact format, no other text:
{{"ai_probability": 0.0}}

Text to analyze:
\"\"\"{text}\"\"\"
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0,
    )

    raw = response.choices[0].message.content.strip()

    try:
        parsed = json.loads(raw)
        score = float(parsed["ai_probability"])
        return max(0.0, min(1.0, score))
    except (json.JSONDecodeError, KeyError, ValueError):
        # Fallback if the model doesn't return clean JSON
        print(f"Warning: could not parse Groq response: {raw}")
        return 0.5


if __name__ == "__main__":
    # Quick standalone test
    test_ai = "Artificial intelligence represents a transformative paradigm shift in modern society. It is important to note that while the benefits of AI are numerous, it is equally essential to consider the ethical implications."
    test_human = "ok so i finally tried that new ramen place downtown and honestly? underwhelming. the broth was fine but they put WAY too much sodium in it."

    print("AI-like text score:", groq_signal(test_ai))
    print("Human-like text score:", groq_signal(test_human))